# uosc (lean overrides)

# Timeline / progress
timeline_size=25
timeline_style=bar
timeline_border=1
timeline_cache=no
progress=always
progress_size=2
progress_line_width=20

# Controls layout
controls=space,speed,space
controls_size=37
controls_margin=8
controls_spacing=2

# Volume
volume=right
volume_size=39
volume_border=1
volume_step=1

# Speed widget
speed_step=0.05
speed_step_is_factor=no

# Menus
menu_item_height=35
menu_min_width=290
menu_padding=4

# Top bar
top_bar=no-border
top_bar_size=45
top_bar_controls=right
top_bar_title=yes
top_bar_alt_title=${filename}
top_bar_alt_title_place=toggle
top_bar_flash_on=video,audio
window_border_size=1

# Behavior
autoload=no

# Appearance
font_scale=1.18
text_border=1.2
border_radius=2
color=foreground=eceff4,foreground_text=2e3440,background=2e3440,background_text=eceff4,curtain=3b4252,success=a3be8c,error=bf616a,match=88c0d0
opacity=timeline=0.8,position=1,chapters=0,speed=0,menu=0.84,title=0,tooltip=0.8,curtain=0.2
refine=text_width
font_bold=yes

# Time display
destination_time=total

# Chapters
chapter_ranges=openings:30abf964,endings:30abf964,intros:3fb95080,outros:3fb95080,ads:c54e4e80
chapter_range_patterns=openings:opening$;endings:^end$,^End$,ending$;intros:preview$, Notice$;outros:credits$

# Misc
show_hidden_files=no
use_trash=no
adjust_osd_margins=yes
