# Minimal bindings to support uosc and a few conveniences.

MBTN_LEFT cycle pause;script-message-to uosc flash-pause-indicator #@click
TAB script-message-to uosc toggle-ui #@press
TAB script-message-to uosc toggle-ui #@release
MOUSE_BTN2 script-binding uosc/menu-blurred

y script-binding uosc/load-subtitles
Y script-binding uosc/subtitles

a cycle window-minimized
q quit-watch-later
