# mpv.conf (lean, UI-focused)

# Video
vo=gpu
gpu-context=wayland
hwdec=auto

# Audio
ao=pipewire

# OSD
osd-font='GeistMono Nerd Font Mono'

# Subtitles
slang=en
sub-file-paths=subs

# Screenshots
screenshot-format=png
screenshot-dir='~/Pictures/mpv'

# Behavior
force-window=yes
cursor-autohide=1000
save-position-on-quit=yes
